# Generated by Django 5.2.2 on 2026-02-17 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacher_external_id_teacher_is_active_teacher_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
