# Generated by Django 5.2.2 on 2026-02-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_subject_department_remove_group_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041e\u0442\u0434\u0435\u043b\u0435\u043d\u0438\u044f',
                'ordering': ['name'],
            },
        ),
    ]
