# Generated by Django 5.2.2 on 2026-02-18 22:05

from django.db import migrations, models


def forwards_map_grade_types(apps, schema_editor):
    Grade = apps.get_model('grading', 'Grade')
    Grade.objects.filter(grade_type='TEST').update(grade_type='GRADE')
    Grade.objects.filter(grade_type__in=['HW', 'LAB']).update(grade_type='PRACT')


def backwards_map_grade_types(apps, schema_editor):
    Grade = apps.get_model('grading', 'Grade')
    Grade.objects.filter(grade_type='GRADE').update(grade_type='TEST')
    Grade.objects.filter(grade_type='PRACT').update(grade_type='LAB')


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_grade_value_five_point_scale'),
    ]

    operations = [
        migrations.RunPython(forwards_map_grade_types, backwards_map_grade_types),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(
                choices=[
                    ('PRACT', '\u041f\u0440\u0430\u043a\u0442\u0438\u0447\u0435\u0441\u043a\u0430\u044f'),
                    ('EXAM', '\u042d\u043a\u0437\u0430\u043c\u0435\u043d'),
                    ('DIFF_CRED', '\u0414\u0438\u0444. \u0437\u0430\u0447\u0435\u0442'),
                    ('GRADE', '\u041e\u0446\u0435\u043d\u043a\u0430'),
                ],
                max_length=10,
                verbose_name='\u0422\u0438\u043f \u043e\u0446\u0435\u043d\u043a\u0438',
            ),
        ),
    ]
