# Generated by Django 5.2.2 on 2026-02-18 22:13

from django.db import migrations, models


def forwards_set_single_grade_type(apps, schema_editor):
    Grade = apps.get_model('grading', 'Grade')
    Grade.objects.exclude(grade_type='GRADE').update(grade_type='GRADE')


def backwards_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_alter_grade_grade_type'),
    ]

    operations = [
        migrations.RunPython(forwards_set_single_grade_type, backwards_noop),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(
                choices=[('GRADE', '\u041e\u0446\u0435\u043d\u043a\u0430')],
                default='GRADE',
                max_length=10,
                verbose_name='\u0422\u0438\u043f \u043e\u0446\u0435\u043d\u043a\u0438',
            ),
        ),
    ]
